### ISSUE TITLE
xfce桌面环境日历大小问题

### ISSUE THREAD

**Issue by shenghuang147** [yetist/lunar-calendar#6]
![图片](https://user-images.githubusercontent.com/65714801/163807704-62af0128-aee4-435b-8848-c1c3e34f9371.png)

![图片](https://user-images.githubusercontent.com/65714801/163807769-037e292b-21bf-4e8f-97e2-d9aad258e419.png)
你好作者大大，问题如图，尝试过设置主题 的 `gtk.css` 文件的字体大小，但是并无效果

将字体设置小后只是字体变小了，农历日历依旧只显示 6 列 5 行。 其他行列都跑到了窗口外，

请教一下有没有什么办法设置 日历 的初始位置。

还有就是农历日历需要点击一下日期或者切换一下年月日才能显示。

这是我的 `clock.c` 
``````bash
1320 
1321       plugin->calendar = lunar_calendar_new ();
1322       gtk_calendar_set_display_options (GTK_CALENDAR (plugin->calendar),
1323                                         GTK_CALENDAR_SHOW_HEADING
1324                                         | GTK_CALENDAR_SHOW_DAY_NAMES
1325                                         | GTK_CALENDAR_SHOW_WEEK_NUMBERS
1326                                         | GTK_CALENDAR_SHOW_DETAILS);
1327       g_signal_connect (G_OBJECT (plugin->calendar_window), "show",
1328                         G_CALLBACK (clock_plugin_calendar_show_event), plugin);
1329       g_signal_connect (G_OBJECT (plugin->calendar_window), "button-press-event",
1330                         G_CALLBACK (clock_plugin_calendar_button_press_event), plugin);
1331       g_signal_connect (G_OBJECT (plugin->calendar_window), "key-press-event",
1332                         G_CALLBACK (clock_plugin_calendar_key_press_event), plugin);
1333       gtk_container_add (GTK_CONTAINER (plugin->calendar_window), plugin->calendar);
1334       gtk_widget_show (plugin->calendar);
1335     }
1336 

``````

这是我的`gtk.css` 文件

``````css
/************
 * Calendar *
 ************/
calendar {
  padding: 12px;
  font-size: 32px;
  border: 1px solid rgba(255, 255, 255, 0.12);
  color: white;
}

calendar:disabled {
  color: rgba(80, 80, 80, 0.5);
}

calendar:selected {
  border-radius: 64px;
}

calendar.header {
  border-style: none none solid;
  border-color: rgba(255, 255, 255, 0.12);
  border-radius: 64px;
}

calendar.highlight {
  color: rgba(255, 255, 255, 0.7);
  font-weight: 500;
}

calendar:indeterminate {
  color: rgba(255, 255, 255, 0.3);
}
``````
